[package]
name = "exporter"
version = "0.0.9"
edition = "2024"

[features]
default = ["display"]
display = []

[dependencies]
dotenvy = "0.15"
anyhow.workspace = true
clap = { version = "4.5.31", features = ["derive"] }
diesel = { version = "2.2.8", features = [
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
] }
tokio = { version = "1.44.0", features = ["full"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
code-api = { path = "../code_api" }
futures.workspace = true
serde.workspace = true
toml = "0.8.20"
toml_edit = "0.22.24"
