name: "exporter"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: run exporter
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RUST_LOG: INFO
        run: |
          cargo r -p exporter --release
