name: "exporter fetch hash"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Install exporter from master
        uses: baptiste0928/cargo-install@v3
        with:
          crate: exporter
          git: https://github.com/nix-community/nix4vscode
          branch: master
      - name: run exporter
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RUST_LOG: DEBUG
        run: |
          exporter --hash --batch-size=8 -o extensions.toml
            - name: Upload wheel artifacts
      - uses: actions/upload-artifact@v4
        with:
          path: extensions.toml
          name: extensions.toml
